#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Dec 30 22:52:52 GMT 2022
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -prj fc_base_top_tb_top_vlog.prj"
xvlog --incr --relax -prj fc_base_top_tb_top_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj fc_base_top_tb_top_vhdl.prj"
xvhdl --incr --relax -prj fc_base_top_tb_top_vhdl.prj 2>&1 | tee -a compile.log

