#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 30 22:53:49 GMT 2022
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim fc_base_top_tb_top_behav -key {Behavioral:sim_1:Functional:fc_base_top_tb_top} -tclbatch fc_base_top_tb_top.tcl -protoinst "protoinst_files/bd_f308.protoinst" -protoinst "protoinst_files/axi_interconnect_bd.protoinst" -protoinst "protoinst_files/bd_9054.protoinst" -log simulate.log"
xsim fc_base_top_tb_top_behav -key {Behavioral:sim_1:Functional:fc_base_top_tb_top} -tclbatch fc_base_top_tb_top.tcl -protoinst "protoinst_files/bd_f308.protoinst" -protoinst "protoinst_files/axi_interconnect_bd.protoinst" -protoinst "protoinst_files/bd_9054.protoinst" -log simulate.log

