######################################################################
#
# File name : top_tb_wave.do
# Created on: Fri Jun 09 20:57:33 BST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
