///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package ex_sim_axi_vip_passthrough_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter ex_sim_axi_vip_passthrough_0_VIP_PROTOCOL           = 2;
      parameter ex_sim_axi_vip_passthrough_0_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter ex_sim_axi_vip_passthrough_0_VIP_INTERFACE_MODE     = 1;
      parameter ex_sim_axi_vip_passthrough_0_VIP_ADDR_WIDTH         = 32;
      parameter ex_sim_axi_vip_passthrough_0_VIP_DATA_WIDTH         = 32;
      parameter ex_sim_axi_vip_passthrough_0_VIP_ID_WIDTH           = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_AWUSER_WIDTH       = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_ARUSER_WIDTH       = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_RUSER_WIDTH        = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_WUSER_WIDTH        = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_BUSER_WIDTH        = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_SUPPORTS_NARROW    = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_BURST          = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_LOCK           = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_CACHE          = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_REGION         = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_QOS            = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_PROT           = 1;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_WSTRB          = 1;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_BRESP          = 1;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_RRESP          = 1;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_ACLKEN         = 0;
      parameter ex_sim_axi_vip_passthrough_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////

typedef axi_passthrough_agent #(ex_sim_axi_vip_passthrough_0_VIP_PROTOCOL, 
                                ex_sim_axi_vip_passthrough_0_VIP_ADDR_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_DATA_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_DATA_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_ID_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_ID_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_AWUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_WUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_BUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_ARUSER_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_RUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_SUPPORTS_NARROW, 
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_BURST,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_LOCK,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_CACHE,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_REGION,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_PROT,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_QOS,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_WSTRB,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_BRESP,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_RRESP,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_ARESETN) ex_sim_axi_vip_passthrough_0_passthrough_t;

typedef axi_passthrough_mem_agent #(ex_sim_axi_vip_passthrough_0_VIP_PROTOCOL, 
                                ex_sim_axi_vip_passthrough_0_VIP_ADDR_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_DATA_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_DATA_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_ID_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_ID_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_AWUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_WUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_BUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_ARUSER_WIDTH,
                                ex_sim_axi_vip_passthrough_0_VIP_RUSER_WIDTH, 
                                ex_sim_axi_vip_passthrough_0_VIP_SUPPORTS_NARROW, 
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_BURST,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_LOCK,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_CACHE,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_REGION,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_PROT,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_QOS,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_WSTRB,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_BRESP,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_RRESP,
                                ex_sim_axi_vip_passthrough_0_VIP_HAS_ARESETN) ex_sim_axi_vip_passthrough_0_passthrough_mem_t;

///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      ex_sim_axi_vip_passthrough_0_passthrough_t  ex_sim_axi_vip_passthrough_0_passthrough;
//      initial begin : START_ex_sim_axi_vip_passthrough_0_SLAVE
//        ex_sim_axi_vip_passthrough_0_passthrough = new("ex_sim_axi_vip_passthrough_0_passthrough", `ex_sim_axi_vip_passthrough_0_PATH_TO_INTERFACE);
//        ex_sim_axi_vip_passthrough_0_passthrough.start_master(); //passthrough in run time master mode
//        ex_sim_axi_vip_passthrough_0_passthrough.start_slave(); //passthrough in run time slave mode
//      end


endpackage : ex_sim_axi_vip_passthrough_0_pkg
