
import top_pkg::*;

interface prefetcher_interface(

    input logic                               core_clk,
    input logic                               resetn,

    input logic regbank_clk,
    input logic regbank_resetn,

    input  logic [AXIL_ADDR_WIDTH-1:0]        s_axi_awaddr,
    input  logic [2:0]                        s_axi_awprot,
    input  logic                              s_axi_awvalid,
    input  logic                              s_axi_awready,
    input  logic [31:0]                       s_axi_wdata,
    input  logic [3:0]                        s_axi_wstrb,
    input  logic                              s_axi_wvalid,
    input  logic                              s_axi_wready,
    input  logic [AXIL_ADDR_WIDTH-1:0]        s_axi_araddr,
    input  logic [2:0]                        s_axi_arprot,
    input  logic                              s_axi_arvalid,
    input  logic                              s_axi_arready,
    input  logic [31:0]                       s_axi_rdata,
    input  logic [1:0]                        s_axi_rresp,
    input  logic                              s_axi_rvalid,
    input  logic                              s_axi_rready,
    input  logic [1:0]                        s_axi_bresp,
    input  logic                              s_axi_bvalid,
    input  logic                              s_axi_bready,

    // NSB -> Prefetcher Interface
    input logic                              nsb_prefetcher_req_valid,
    input logic                              nsb_prefetcher_req_ready,
    input NSB_PREF_REQ_t                     nsb_prefetcher_req,

    input logic                              nsb_prefetcher_resp_valid, // valid only for now
    input NSB_PREF_RESP_t                    nsb_prefetcher_resp,

    // Prefetcher Adjacency Read Master -> AXI Memory Interconnect
    input logic [33:0]                       prefetcher_adj_rm_axi_interconnect_axi_araddr,
    input logic [1:0]                        prefetcher_adj_rm_axi_interconnect_axi_arburst,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_arcache,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_arid,
    input logic [7:0]                        prefetcher_adj_rm_axi_interconnect_axi_arlen,
    input logic [0:0]                        prefetcher_adj_rm_axi_interconnect_axi_arlock,
    input logic [2:0]                        prefetcher_adj_rm_axi_interconnect_axi_arprot,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_arqos,
    input logic [2:0]                        prefetcher_adj_rm_axi_interconnect_axi_arsize,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_arvalid,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_arready,
    input logic [33:0]                       prefetcher_adj_rm_axi_interconnect_axi_awaddr,
    input logic [1:0]                        prefetcher_adj_rm_axi_interconnect_axi_awburst,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_awcache,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_awid,
    input logic [7:0]                        prefetcher_adj_rm_axi_interconnect_axi_awlen,
    input logic [0:0]                        prefetcher_adj_rm_axi_interconnect_axi_awlock,
    input logic [2:0]                        prefetcher_adj_rm_axi_interconnect_axi_awprot,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_awqos,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_awready,
    input logic [2:0]                        prefetcher_adj_rm_axi_interconnect_axi_awsize,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_awvalid,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_bid,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_bready,
    input logic [1:0]                        prefetcher_adj_rm_axi_interconnect_axi_bresp,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_bvalid,
    input logic [511:0]                      prefetcher_adj_rm_axi_interconnect_axi_rdata,
    input logic [3:0]                        prefetcher_adj_rm_axi_interconnect_axi_rid,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_rlast,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_rready,
    input logic [1:0]                        prefetcher_adj_rm_axi_interconnect_axi_rresp,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_rvalid,
    input logic [511:0]                      prefetcher_adj_rm_axi_interconnect_axi_wdata,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_wlast,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_wready,
    input logic [63:0]                       prefetcher_adj_rm_axi_interconnect_axi_wstrb,
    input logic                              prefetcher_adj_rm_axi_interconnect_axi_wvalid,

    // Prefetcher Message Read Master -> AXI Memory Interconnect
    input logic [33:0]                       prefetcher_msg_rm_axi_interconnect_axi_araddr,
    input logic [1:0]                        prefetcher_msg_rm_axi_interconnect_axi_arburst,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_arcache,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_arid,
    input logic [7:0]                        prefetcher_msg_rm_axi_interconnect_axi_arlen,
    input logic [0:0]                        prefetcher_msg_rm_axi_interconnect_axi_arlock,
    input logic [2:0]                        prefetcher_msg_rm_axi_interconnect_axi_arprot,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_arqos,
    input logic [2:0]                        prefetcher_msg_rm_axi_interconnect_axi_arsize,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_arvalid,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_arready,
    input logic [33:0]                       prefetcher_msg_rm_axi_interconnect_axi_awaddr,
    input logic [1:0]                        prefetcher_msg_rm_axi_interconnect_axi_awburst,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_awcache,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_awid,
    input logic [7:0]                        prefetcher_msg_rm_axi_interconnect_axi_awlen,
    input logic [0:0]                        prefetcher_msg_rm_axi_interconnect_axi_awlock,
    input logic [2:0]                        prefetcher_msg_rm_axi_interconnect_axi_awprot,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_awqos,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_awready,
    input logic [2:0]                        prefetcher_msg_rm_axi_interconnect_axi_awsize,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_awvalid,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_bid,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_bready,
    input logic [1:0]                        prefetcher_msg_rm_axi_interconnect_axi_bresp,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_bvalid,
    input logic [511:0]                      prefetcher_msg_rm_axi_interconnect_axi_rdata,
    input logic [3:0]                        prefetcher_msg_rm_axi_interconnect_axi_rid,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_rlast,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_rready,
    input logic [1:0]                        prefetcher_msg_rm_axi_interconnect_axi_rresp,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_rvalid,
    input logic [511:0]                      prefetcher_msg_rm_axi_interconnect_axi_wdata,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_wlast,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_wready,
    input logic [63:0]                       prefetcher_msg_rm_axi_interconnect_axi_wstrb,
    input logic                              prefetcher_msg_rm_axi_interconnect_axi_wvalid,

    // Prefetcher Weight Bank Read Master -> AXI Memory Interconnect
    input logic [33:0]                       prefetcher_weight_bank_rm_axi_interconnect_axi_araddr,
    input logic [1:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arburst,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arcache,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arid,
    input logic [7:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arlen,
    input logic [0:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arlock,
    input logic [2:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arprot,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arqos,
    input logic [2:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_arsize,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_arvalid,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_arready,
    input logic [33:0]                       prefetcher_weight_bank_rm_axi_interconnect_axi_awaddr,
    input logic [1:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awburst,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awcache,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awid,
    input logic [7:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awlen,
    input logic [0:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awlock,
    input logic [2:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awprot,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awqos,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_awready,
    input logic [2:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_awsize,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_awvalid,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_bid,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_bready,
    input logic [1:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_bresp,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_bvalid,
    input logic [511:0]                      prefetcher_weight_bank_rm_axi_interconnect_axi_rdata,
    input logic [3:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_rid,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_rlast,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_rready,
    input logic [1:0]                        prefetcher_weight_bank_rm_axi_interconnect_axi_rresp,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_rvalid,
    input logic [511:0]                      prefetcher_weight_bank_rm_axi_interconnect_axi_wdata,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_wlast,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_wready,
    input logic [63:0]                       prefetcher_weight_bank_rm_axi_interconnect_axi_wstrb,
    input logic                              prefetcher_weight_bank_rm_axi_interconnect_axi_wvalid,

    // Message Channels: AGE -> Prefetcher Feature Bank
    input logic [MESSAGE_CHANNEL_COUNT-1:0]                  message_channel_req_valid,
    input logic [MESSAGE_CHANNEL_COUNT-1:0]                  message_channel_req_ready,
    input MESSAGE_CHANNEL_REQ_t [MESSAGE_CHANNEL_COUNT-1:0]  message_channel_req,

    input logic [MESSAGE_CHANNEL_COUNT-1:0]                  message_channel_resp_valid,
    input logic [MESSAGE_CHANNEL_COUNT-1:0]                  message_channel_resp_ready,
    input MESSAGE_CHANNEL_RESP_t [MESSAGE_CHANNEL_COUNT-1:0] message_channel_resp,

    // Weight Channels: FTE -> Prefetcher Weight Bank
    input logic                 [top_pkg::PRECISION_COUNT-1:0] weight_channel_req_valid,
    input logic                 [top_pkg::PRECISION_COUNT-1:0] weight_channel_req_ready,
    input WEIGHT_CHANNEL_REQ_t  [top_pkg::PRECISION_COUNT-1:0] weight_channel_req,

    input logic                 [top_pkg::PRECISION_COUNT-1:0] weight_channel_resp_valid,
    input logic                 [top_pkg::PRECISION_COUNT-1:0] weight_channel_resp_ready,
    input WEIGHT_CHANNEL_RESP_t [top_pkg::PRECISION_COUNT-1:0] weight_channel_resp,

    input  logic [MESSAGE_CHANNEL_COUNT-1:0]                                           scale_factor_queue_pop,
    input  logic [MESSAGE_CHANNEL_COUNT-1:0] [SCALE_FACTOR_QUEUE_READ_WIDTH-1:0]       scale_factor_queue_out_data,
    input  logic [MESSAGE_CHANNEL_COUNT-1:0]                                           scale_factor_queue_out_valid,
    input  logic [MESSAGE_CHANNEL_COUNT-1:0] [$clog2(SCALE_FACTOR_QUEUE_READ_DEPTH):0] scale_factor_queue_count,
    input  logic [MESSAGE_CHANNEL_COUNT-1:0]                                           scale_factor_queue_empty,
    input  logic [MESSAGE_CHANNEL_COUNT-1:0]                                           scale_factor_queue_full

);

endinterface