webtalk_init -webtalk_dir /home/pg519/nfshome/fuzzy_carnival/fuzzy_carnival_base/fuzzy_carnival_base.sim/sim_1/behav/xsim/xsim.dir/fc_base_top_tb_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 30 23:00:08 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210646553_178599480_210671900_304" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7197e9e9-a347-4365-9bef-2b4e40d930aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2492c2744f9842449903afdf181c7b52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.006 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "405.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "115.40_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "529332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1173980534 -regid "210646553_178599480_210671900_304" -xml /home/pg519/nfshome/fuzzy_carnival/fuzzy_carnival_base/fuzzy_carnival_base.sim/sim_1/behav/xsim/xsim.dir/fc_base_top_tb_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/pg519/nfshome/fuzzy_carnival/fuzzy_carnival_base/fuzzy_carnival_base.sim/sim_1/behav/xsim/xsim.dir/fc_base_top_tb_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/pg519/nfshome/fuzzy_carnival/fuzzy_carnival_base/fuzzy_carnival_base.sim/sim_1/behav/xsim/xsim.dir/fc_base_top_tb_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
